version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring_test
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
    - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  postgres_data:
  pgadmin:


