/*
 * File: app/view/AddDocumentWindow.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AddDocumentWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.adddocumentwindow',

    requires: [
        'MyApp.view.AddDocumentWindowViewModel',
        'MyApp.view.AddDocumentWindowViewController',
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button'
    ],

    controller: 'adddocumentwindow',
    viewModel: {
        type: 'adddocumentwindow'
    },
    reference: 'NewDocomentWindow',
    height: 240,
    id: 'newDocomentWindow',
    width: 400,
    title: 'Добавление нового документа',

    items: [
        {
            xtype: 'form',
            reference: 'AddDocumentForm',
            height: 205,
            bodyPadding: 10,
            jsonSubmit: true,
            method: 'POST',
            standardSubmit: false,
            url: '/api/documents',
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Заголовок',
                    name: 'header',
                    allowBlank: false
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'Описание',
                    name: 'description',
                    allowBlank: false
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    fieldLabel: 'Заключение',
                    name: 'footer',
                    allowBlank: false
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Отмена',
                            listeners: {
                                click: 'onCancelButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Добавить',
                            listeners: {
                                click: 'onAddButtonClick'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});