/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    requires: [
        'MyApp.view.MyTabPanelViewModel',
        'MyApp.view.MyTabPanelViewController',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.TextArea',
        'Ext.ux.grid.plugin.AutoSelector',
        'Ext.grid.plugin.CellEditing',
        'Ext.toolbar.Toolbar',
        'Ext.grid.filters.filter.String',
        'Ext.grid.filters.Filters',
        'Ext.toolbar.Fill',
        'Ext.form.field.ComboBox'
    ],

    controller: 'mytabpanel',
    viewModel: {
        type: 'mytabpanel'
    },
    height: 636,
    activeTab: 0,
    tabPosition: 'left',
    tabRotation: '0',

    items: [
        {
            xtype: 'panel',
            width: 700,
            layout: 'fit',
            title: 'Общие поля',
            tabConfig: {
                xtype: 'tab',
                height: 60,
                maxHeight: 60,
                maxWidth: 120,
                minHeight: 60,
                minWidth: 120,
                width: 120
            },
            items: [
                {
                    xtype: 'gridpanel',
                    reference: 'DocumentsGrid',
                    height: 260,
                    width: 440,
                    title: 'Просмотр и редактирование общих полей документа',
                    store: 'DocumentsStore',
                    bind: {
                        selection: '{documentGridSelection}'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'id',
                            text: 'id'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 200,
                            dataIndex: 'header',
                            text: 'Заголовок',
                            editor: {
                                xtype: 'textfield',
                                allowBlank: false
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 300,
                            dataIndex: 'description',
                            text: 'Описание',
                            editor: {
                                xtype: 'textareafield',
                                allowBlank: false
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 300,
                            dataIndex: 'footer',
                            text: 'Заключение',
                            editor: {
                                xtype: 'textareafield',
                                allowBlank: false
                            }
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'gridautoselector'
                        },
                        {
                            ptype: 'cellediting'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            itemId: 'mytoolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'x-fa fa-plus',
                                    text: 'Добавить документ',
                                    listeners: {
                                        click: 'onAddDocumentButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'x-fa fa-minus',
                                    text: 'Удалить документ',
                                    bind: {
                                        disabled: '{!documentGridSelection}'
                                    },
                                    listeners: {
                                        click: 'onDeleteDocumentButtonClick'
                                    }
                                }
                            ]
                        }
                    ],
                    listeners: {
                        selectionchange: 'onGridpanelSelectionChange'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            layout: 'fit',
            title: 'Разделы',
            tabConfig: {
                xtype: 'tab',
                height: 60,
                maxHeight: 60,
                maxWidth: 120,
                minHeight: 60,
                minWidth: 120,
                width: 120
            },
            items: [
                {
                    xtype: 'gridpanel',
                    reference: 'SectionGrid',
                    itemId: 'mygridpanel1',
                    title: 'Просмотр и редактирование разделов документа',
                    store: 'SectionsStore',
                    bind: {
                        selection: '{sectionGridSelection}'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 400,
                            dataIndex: 'title',
                            text: 'Заголовок',
                            editor: {
                                xtype: 'textfield',
                                allowBlank: false
                            },
                            filter: {
                                type: 'string'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 400,
                            dataIndex: 'text',
                            text: 'Текст',
                            editor: {
                                xtype: 'textareafield',
                                allowBlank: false
                            },
                            filter: {
                                type: 'string'
                            }
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'cellediting'
                        },
                        {
                            ptype: 'gridautoselector'
                        },
                        {
                            ptype: 'gridfilters'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'x-fa fa-plus',
                                    text: 'Добавить раздел',
                                    listeners: {
                                        click: 'onAddSectionButtonClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'x-fa fa-minus',
                                    text: 'Удалить раздел',
                                    bind: {
                                        disabled: '{!SectionGrid.selection}'
                                    },
                                    listeners: {
                                        click: 'onDeleteSectionButtonClick'
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'combobox',
                                    reference: 'filterComboBox',
                                    fieldLabel: 'Документ:',
                                    editable: false,
                                    displayField: 'header',
                                    store: 'DocumentsStore',
                                    valueField: 'id',
                                    listeners: {
                                        change: 'onFilterChange'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'x-fa fa-trash',
                                    text: 'Сбросить фильтр',
                                    listeners: {
                                        click: 'onClearFilterButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            reference: 'ViewTab',
            html: '<div id="viewDocumentDiv">Документ не выбран!</div>',
            id: 'viewTab',
            bodyPadding: 10,
            title: 'Просмотр',
            tabConfig: {
                xtype: 'tab',
                height: 60,
                maxHeight: 60,
                maxWidth: 120,
                minHeight: 60,
                minWidth: 120,
                width: 120
            },
            listeners: {
                activate: 'onViewTabActivate'
            }
        }
    ]

});